source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/SkyroadJP/Cocoapods-Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.3'

pod 'eigen'

target 'eigenTest (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eigenTest (iOS)

end

target 'eigenTest (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eigenTest (macOS)

end
